[tool.poetry]
name = "mitmproxy2swagger"
version = "0.4.0"
description = ""
authors = ["alufers <alufers@wp.pl>"]

[tool.poetry.dependencies]
python = "^3.5"
mitmproxy = "^8.0.0"
"ruamel.yaml" = "^0.17.21"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mitmproxy2swagger = 'mitmproxy2swagger.mitmproxy2swagger:main'
